### PR TITLE
Create initial project structure and introduce interfaces

### PR DESCRIPTION
**Pull request by kamaek**
Now, we have 2 projects within the solution: `Logic` and `Forms`.

`Logic` contains newly introduced interfaces, that should be implemented further. Some interfaces still have missing documentation and flaws in design. I propose to resolve the remaining issues later.

`Forms` contains an empty `MainForm` and have a dependency on `Logic`, so classes from `Logic` can be used in `Forms`.

### CODE REVIEW

**Comment by kamaek** [comment]
Someone, review it please.

**Comment by karim-safin** [comment]
What is `CorrectWords`? If it is the list of all possible words, then it should be renamed to `PossibleWords` or `FeasibleWords`.
If it is the list of all words that can be placed on the field at the current moment, then this decision needs more discussion, since `interface GameField` already contains all the words that have been placed, so the possibility of placing a word could be calculated just from all feasible words and words that have already been placed.
Is it possible to specify more methods in the `interface Game`? Maybe it should be an abstract class? It is already known that it should be a state machine that calculates the results of players' moves and updates it's own state accordingly.
If I have understood you correctly, you are going to perform all the game logic inside the class that implements the `interface Action`. But calculating a move requires not only the state of the game field, but also rules, the scores of the players, time passed since the start of the turn and, possibly, something else. Again, my arguments are the same as in the previous paragraph -- `Game` should be a state machine because it is the natural representation of a game, and therefore `Action` should, IMO, be an `enum`.
I don't see anything wrong with other interfaces I haven't mentioned.
What do you think of all this?

**Comment by kamaek** [comment]
@karim-safin you can attach a comment to a line of a source file, by the way. Please take a look at this short [article](https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/).

1. I have made changes with `CorrectWords`.

2. What can users do with `Game`? They can start a game and that's all, I believe.

3. `Action` is an interaction with `GameField`.
    * A specific action may require some additional data, you are right, but it is implementation details of an `Action`. E.g. `EndTurn` can have `Player` field to update its score, but this is not a generic parameter for all actions. What is general for all actions besides of `GameField`?
    * An `Action` has some behavior, so how it can be an enum?

**Comment by timurolshevskiy** [comment]
Hi guys, I am a bit surprised to see this. How did you decided to start such project? And why did you choose C#? Is it university task? Sorry for interfering.

**Comment by kamaek** [comment]
Hello, if you are interested in our project, please ask your questions [here](https://github.com/kamaek/Balda-Game/issues) :D 

Yes, its our university task. We are doing some kind of a re-engineering for this [implementation](https://github.com/karim-safin/Balda), which was written in C#. So we have decided to use C# now either, just for "simplicity".

**Pull request merged**
